[package]
name = "recocido_simulado"
version = "2.0.0"
authors = ["DavidFHCh <davfep_96@ciencias.unam.mx>"]

[dependencies]
rusqlite = "0.12.0"
rand = "0.3.16"
config = "0.6"
time = "0.1.38"
gnuplot = "0.0.22"
scoped_threadpool = "0.1.*"
